### ISSUE TITLE
marking unread comments

### ISSUE THREAD

**Issue by Tealk** [thunder-app/thunder#100]
**Is your feature request related to a problem? Please describe.**
in lemmy there is a small message with (1 new) comments, this is very helpful to see if there are new comments

**Describe the solution you'd like**
maybe you could highlight the comments icon when there are new comments

**Describe alternatives you've considered**
alternatively also display a small number showing the new comments

**Comment by shortwavesurfer2009** [comment]
Do you by chance adding a little dot to the inbox logo to let you know there is something new?

**Comment by Tealk** [comment]
no not the inbox, but at the post overview I meant, but yes at the inbox that would also be a good idea, although I do not know if the current was already in the update with it.

**Comment by CTalvio** [comment]
Posts that get more comments since you last visited them, show this:
![image](https://github.com/hjiangsu/thunder/assets/4365015/eff80f8e-7b68-423b-aee9-c97380bec000)

The new comments are also highlighted:
![image](https://github.com/hjiangsu/thunder/assets/4365015/a9e66cac-d033-40df-9517-c2d512c7c670)

**Comment by CTalvio** [comment]
This is now basically implemented, but does not quite work right and as such is still commented out.

We will need to find out how the mark comments on a post as read, before this can work properly.

**Comment by CTalvio** [comment]
Added as of #1094 with a small fix in #1103
