### ISSUE TITLE
Add "Scaled" to the "Default Sort" setting

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1002]
**Is your feature request related to a problem? Please describe.**
The default sort type setting does not contained the option for "scaled"
![Screenshot_20231222-160236](https://github.com/thunder-app/thunder/assets/7829231/d0895ba7-d072-4f46-9d48-df3434118fd0)

**Describe the solution you'd like**
Add the "Scaled" sort-type to the default sort type option.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by micahmo** [comment]
Previous discussion for reference! Thanks!

https://github.com/thunder-app/thunder/pull/829#discussion_r1365879707

**Comment by hjiangsu** [comment]
I'll just add this in here: https://fedidb.org/software/lemmy

I believe we should wait a bit longer until the majority of instances have migrated to 0.19.x before adding the new sorts as options. Once the top 30~40 instances have migrated to 0.19.x, we can enable these options in the settings. This should cover the majority of users.

**Comment by K4LCIFER** [comment]
> I'll just add this in here: https://fedidb.org/software/lemmy
> 
> I believe we should wait a bit longer until the majority of instances have migrated to 0.19.x before adding the new sorts as options. Once the top 30~40 instances have migrated to 0.19.x, we can enable these options in the settings. This should cover the majority of users.

Would it be worth it to just have Thunder check what version the server is running, or check if the server offers a scaled sort, and then dynamically change the UI depending on what the server offers?

**Comment by hjiangsu** [comment]
> Would it be worth it to just have Thunder check what version the server is running, or check if the server offers a scaled sort, and then dynamically change the UI depending on what the server offers?

The one issue here is that the sort type is global across all instances/servers, and it is not synced per account. This means that if a user chooses one of the new sort types, there should be a secondary option to fallback to if the instance does not support the new sort type. Doing this would take a bit more work on our part and it would be a short term solution (that would be removed once most instances have migrated to 0.19.x)

I believe the better approach here (and feel free to let me know if you think otherwise) is to make it so that the default sort type is synced with your account (Lemmy) settings since that is already part of Lemmy itself. Then, we could re-use the existing sort type setting to be used for anonymous (non-logged in) accounts.

**Comment by orangeNgreen** [comment]
Now that most instances have upgraded to 0.19.x, it might be a good time to implement Scaled sort as a default setting.

**Comment by daviessm** [comment]
Yeah, I think that now 0.3.0 is out this is a good candidate for the next release.
