### ISSUE TITLE
Unable to follow "Lemmy Links"

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1006]
**Description**  
You appear to be unable to follow/tap a [Lemmy Link](https://github.com/LemmyNet/lemmy/issues/2987) despite it being highlighted blue.

**How to Reproduce**  
1. Locate a Lemmy Link
2. Tap on it
3. Observer that nothing happens

**Expected Behavior**  
I would expect that the specific Lemmy link would be followed

**Screenshots**  
None, at the moment. I'll update this post with a video confirmation when I come across another Lemmy Link.

**Device & App Version:**  
 - Device: Google Pixel 6
 - OS: Android 14
 - App Version 0.2.7-6

**Additional Context** 
None

**Comment by hjiangsu** [comment]
I wonder if this is related to #997

**Comment by micahmo** [comment]
Ditto! As far as I know, we support Lemmy links for users, communities, posts, and comments in all of the web formats and hyperlinks, plus a few! If navigation doesn't work, it may be because it's federated from a different platform, like was fixed in #997, or because it hasn't federated to your current instance. Like @hjiangsu, and example of a bad link would really help!

**Comment by K4LCIFER** [comment]
I think I can close this, as I haven't been able to find a link that confirms this issue.
