### ISSUE TITLE
Jpeg XL breaks things pretty badly. 

### ISSUE THREAD

**Issue by cooperaj** [thunder-app/thunder#1073]
**Description** 
JPEG XL (JXL) images cause Thunder to break output. They're not technically supported by Pictrs so are not used often. 

**How to Reproduce**  
1. Go to https://lemmy.world/post/11021604
2. Screen briefly loads then changes to an empty black screen

**Expected Behavior**  
Even if the image fails the comment thread should still be visible. 

**Device & App Version:**  
 - Device: Pixel 6 Pro
 - OS: Android 14
 - App Version: 0.2.9-1

**Comment by micahmo** [comment]
I wonder if we'd need to open an issue with Extended Image.

**Comment by hjiangsu** [comment]
Interesting - it looks like it renders properly on iOS (which coincidentally relates to the meme 😆)

![IMG_1575](https://github.com/thunder-app/thunder/assets/30667958/d0f34ae3-669d-4454-abfc-9b9d7675224a)

**Comment by micahmo** [comment]
I'm not sure if it helps, but an exception is thrown here.

![image](https://github.com/thunder-app/thunder/assets/7417301/4832dfd7-2174-4833-a401-25df99178af9)

And here is the call stack.

![image](https://github.com/thunder-app/thunder/assets/7417301/48bec574-d1c8-43f3-929e-a73d30c54011)

And although it's not in the stack, I assume this comes back to an `ExtendedImage.network` constructor.

**Comment by hjiangsu** [comment]
So I took a deeper look into this, and it seems like this may be out of scope to support `jxl` at this moment. Flutter itself does not support `jxl` as mentioned here: https://github.com/flutter/flutter/issues/113476. Flutter does provide fallback to using the OS's media codecs so it depends on the OS. For example, Apple currently has support for `jxl` but Android still has an open issue for this: https://issuetracker.google.com/issues/259900694?pli=1

It seems like the only solutions here are to either create a `jxl` codec plugin, or have some resolution on Android's end to implement support for `jxl`. 

What we can do, is add in a check to see if its `jxl`, and either fallback to showing an error, or request the image in a different format using `?format=` for the pictrs endpoint.

**Comment by hjiangsu** [comment]
Just a quick update on this, I've fixed the issue where the comment section breaks when attempting to load a failed image. This handles the more generic case where unsupported formats should fallback gracefully.

In terms of providing support for `jxl`, that may come in the future. The problem with my suggestion previously is that not all images may come from `pictrs`, so some additional thought will be needed to come up with a more robust solution. 

That being said, since `pictrs` does not technically support `jxl`, I dont believe there will be too many instances of this happening so we can revisit `jxl` support in the future (and maybe then, it'll be more widely adopted!)
