### ISSUE TITLE
Mute audio by default

### ISSUE THREAD

**Issue by Kommynct** [thunder-app/thunder#1161]
### Feature Description

If I open a post, i'd rather it not play audio unless I unmute it.

It'd be nice to have a separate toggle for nsfw posts, that way sfw posts could still play audio by default.

**Comment by hjiangsu** [comment]
Thanks for the request! Just double checking, but is this issue also related to #1177? By this, I mean that tapping on a link opens the in-app browser which then triggers the video player.

If so, there is no current way to do this because that video player is handled by the system (in-app browser) rather than by Thunder. In-app video support is currently WIP. However, once the in-app video is implemented, this should be possible.

**Comment by Kommynct** [comment]
Yeah, I didn't notice there was no in-app video player when I made this ticket, i was just looking for the option and couldn't find it, this should be saved for when the in-app video player is added.

**Comment by hjiangsu** [comment]
As mentioned in the other ticket, I'll be adding a badge to indicate when a link is a direct link to a video (so that you can manually adjust the system audio before tapping on the link). This should help temporarily while the video player is being worked on!

**Comment by hjiangsu** [comment]
Just an update on this - v0.4.0 has been released with experimental video support. There is an option to automatically mute videos in Settings -> Video.

Since this is the case, I'll go ahead and close this issue. If you notice any issues with this, please open a new issue. Thanks!
