### ISSUE TITLE
Hide post via action/gesture

### ISSUE THREAD

**Issue by IAmCaligvla** [thunder-app/thunder#1176]
### Feature Description

An action to hide posts using either swipe gestures or the actions menu, like how _Sync for Lemmy_ does it.

**Comment by hjiangsu** [comment]
Thanks for the request! I would like to clarify a bit more about the behaviour of hiding posts. Is the hide post action a temporary hide (that reappears after a refresh), or a more permanent hide?

**Comment by IAmCaligvla** [comment]
Ideally a more permanent hide, so you can clean up your feed of undesired posts. Sync has an experimental feature that keeps posts hidden even after a refresh, I imagine it would be very useful to have something similar if possible.

**Comment by hjiangsu** [comment]
Thanks for the response! I believe that Lemmy itself is adding some capabilities for hiding posts (see https://github.com/LemmyNet/lemmy/issues/1403)

I think the best course of action here is to wait until that feature is released so that hidden posts are synced across accounts (rather than it being local to a specific app)
