### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by Krishna-G-OP** [thunder-app/thunder#1179]
I am a web developer, I'd be happy to contribute to your project and its continued development. I've reviewed the project and believe my skills in web development could be valuable. I see that there is no current active website of this project so I think i can contribute to the process of web development as I'm interested in exploring contribution opportunities.
Please let me know how I can best get involved based on the project's current needs.

**Comment by hjiangsu** [comment]
Thanks for your interest!

Right now, there is a very simple user-facing site for Thunder (https://thunderapp.dev). It's not being actively worked on because of other priorities but if you're interested in working on that, let me know! The source for the current site is not yet open because the main purpose of it was to host an external server for Thunder related features (e.g., #1095)

**Comment by Krishna-G-OP** [comment]
Yes, I am interested

**Comment by hjiangsu** [comment]
Awesome! What languages/frameworks are you familiar with?

For some context the site is using React + TypeScript but that can be changed since there's not much done yet.

**Comment by Krishna-G-OP** [comment]
Sorry for late response but I was sleeping

My reply:
I use pure web development tech
