### ISSUE TITLE
Tap Home button to scroll to top of feed/return to main feed?

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#149]
In most reddit/lemmy apps I've tried, tapping the home button serves a few additional purposes beyond returning to the feed view from a different nav bar section - most of the time it can be:

- pressed while in feed view to auto-scroll back to the top
- pressed while scrolling through a specific community to return to the "main feed"

If possible it would be great to see these functions implemented in Thunder at some point (if you also feel they would be useful, of course!)

**Comment by kaibagley** [comment]
Since this _seems_ like a simple thing to implement, I'm keen to try to do this. However I'm **very** new to dart/flutter and have only been learning it to hopefully contribute a bit to this amazing app.

That being said, if anyone has any tips off the top of their heads to do this please let me know, who knows how long it'll take me to figure it out

**Comment by hjiangsu** [comment]
This one is a little bit more tricky to figure out than it initially seems - the bottom nav bar is not directly connected to the community/feed screen so you would have to tie in some logic to be able to control the scroll of the community/feed screen from the main bottom nav bar screen

The bottom app bar is in the main view, and there's a subview that shows the feed. In order to implement this, you would have to 
- pass a `ScrollController` from the feed/community page up to that main view
- detect when the user taps on the bottom nav bar option when they are currently in the feed view
- use that `ScrollController` to move the scroll position back up

However, do feel free to play around with it and see if you can get it to work!

**Comment by kaibagley** [comment]
By the way if anyone wants to just get this done that's fine, I don't want to hold features up just for the sake of my own learning

**Comment by kaibagley** [comment]
Is there a way to use Bloc for this? Rather than passing a `ScrollController` around? I'm having trouble understanding the best way to do this...

**Comment by hjiangsu** [comment]
You could use Bloc for this as well. Here's an initial and very rough idea:

The BottomNavBar is connected to the ThunderBloc
- When you perform a secondary tap on the bottomNavBar icon while you're in the feed view, you can create a new event `context.read<ThunderBloc>().add(OnScrollToTopEvent());
- Within the Bloc event, you can set the add in a new state variable `scrollToTopId` which is a randomly generated string to treat as a token to check for changes to that variable
- Within the main view, add in a BlocListener which listens to that specific state variable (you can use `listenWhen`) This will give you access to the previous and current state of the bloc
- If the state (token) changes for the `scrollToTopId`, then trigger the scrollController to go back up to the top
