### ISSUE TITLE
Hide Post Gesture Not Working on iOS 18

### ISSUE THREAD

**Issue by 0oWow** [thunder-app/thunder#1569]
### Bug Description

After enabling the "hide" Post swipe gesture, a post shows the circle with a slash through it, as expected, but it just bounces back to resting position with no other effect.  The post remains visible, even after a refresh of the feed.  

### Expected Behaviour

1. Enable "hide" Post swipe gesture.
2. Swipe post on feed to activate hide gesture.
3. Post hides itself from the feed.

### Steps to Reproduce

1. Activate hide Post swipe gesture.
2. Swipe post.

### Additional Context

If there is a way to submit logs, I'm willing to send them but I don't see the option.

### App Version

0.5.1

### Device

iPhone 16 Pro

### OS

iOS 18.1 Public Beta

**Comment by micahmo** [comment]
Hey @0oWow, you might have the "Show Hidden Posts" setting enabled, which would keep the hidden posts on your feed and only indicate that they're hidden with an icon.

[Thunder Setting: General > Feed > Show Hidden Posts](thunder://setting-setting_general_show_hidden_posts)

If you have that setting on, try turning it off and see if that helps! Also you might have to restart the app after changing that setting.

**Comment by 0oWow** [comment]
Hi, thanks for the reply, however I had checked that before posting.  It was off.  I just checked again right now to be sure, it is disabled, but hiding still does not work.

**Comment by micahmo** [comment]
Thanks for confirming! Just to check, does the hidden icon appear on the post after you swipe it? Also, what instance are you using?

**Comment by 0oWow** [comment]
Yes, the hide icon shows up when trying to swipe, but it does nothing but look pretty.  I'm using lemmy.world.

**Comment by 0oWow** [comment]
To be clear though, the hide icon goes back into hiding after I finish the swipe action.

**Comment by micahmo** [comment]
> I'm using lemmy.world.

Got it! This is the problem. lemmy.world is still on Lemmy version 0.19.3, which does not support post hiding. Here's what post hiding looks like on lemmy.ca, which uses Lemmy version 0.19.5.


https://github.com/user-attachments/assets/f16c34ff-de64-4b99-aab2-b25ae22260a8

You'll see it uses an eyeball icon, rather than the circle with the line through it. The circle with the line is _supposed_ to communicate the fact that the chosen gesture is not applicable (or that you have chosen no gesture for that slot). However, in the case of post hiding, I can certainly see how that icon would imply that the hiding action is in effect.

I'm not really sure the best way to communicate this. We can't show or hide the post hiding gesture option in settings based on which instance you're connected to, because you could switch to another instance any time. If you have any suggestions to make this limitation more clear, please let us know!

**Comment by 0oWow** [comment]
Oooh I see, yeah I don't get the 'eye' symbol, I get the circle with line through it.  I'll switch to another instance and report back.  Thanks for pointing me in the right direction!

**Comment by 0oWow** [comment]
OK, I already had another instance signed up that I forgot about (lemm.ee).  Hiding works great.  This issue can be closed.  Thanks for the help!

**Comment by 0oWow** [comment]
Closing as resolved.

**Comment by hjiangsu** [comment]
Thanks @micahmo for helping troubleshoot the issue, and I'm glad the issue has been resolved!
