### ISSUE TITLE
Post language selection

### ISSUE THREAD

**Issue by kyrawertho** [thunder-app/thunder#157]
Some communities require a language to be selected when posting a comment. The app doesn't have this option and shows a language not allowed error when submitting a post.

**Describe the solution you'd like**
Add a language selection dropdown when needed.

![image](https://github.com/hjiangsu/thunder/assets/63714528/0aa083bb-049b-4913-b1f5-e39ce36d4712)

**Comment by Tealk** [comment]
Yes that would be a very important feature, currently I always have to switch to the browser when I want to write in other languages.

**Comment by Fmstrat** [comment]
This should be solved two ways, and could be done in two steps to manage for one population first:

1) Make a default comment language settings in General. This will cover off on a huge number of cases of people can select English and have the post of comments default to that if the community requires it.
2) Next up, is allow for language selection on post of new comment.

**Comment by Tealk** [comment]
Is there anything new on this yet, we should prioritize the feature, some instances now exclude posts that don't have a language specification.

**Comment by micahmo** [comment]
This is being worked on in #893!

**Comment by hjiangsu** [comment]
This has been added for creating/editing posts as indicated by the title of the issue. However, this is not yet implemented for creating/editing comments.

I think it would be best to open up a new issue for selecting language when creating/editing comments to keep things more organized. I'll close this issue but let me know if you think otherwise!
