### ISSUE TITLE
No single collapsed comments

### ISSUE THREAD

**Issue by Tealk** [thunder-app/thunder#265]
**Is your feature request related to a problem? Please describe.**
Starting at the 5 level, each comment is collapsed one at a time. Unfolding each comment is exhausting

**Describe the solution you'd like**
That only the 5 is collapsed and all levels below are not, so that you can read the complete conversation with one click

**Describe alternatives you've considered**
Tefere levels are always unfolded with when you unfold a higher one, maybe with an option because not everyone likes it?

**Comment by hjiangsu** [comment]
I have sort-of added this in the latest release. When you expand a comment after level 4/5, it will by default expand all the child comments.

I'm working towards getting the app to remember some of the states of each comment, so that collapsed/expanded comments will stay as they are (as long as you dont leave the post itself for now)

**Comment by hjiangsu** [comment]
I think the original issue has been solved.

I still have the ongoing issue with trying to memorize the collapsed state of comments, but just to clean up the backlog, I'll close this issue! Let me know if you'd like me to reopen it.
