### ISSUE TITLE
Mysterious block in Reply screen

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#295]
For some reason there's this random block that lives above my keyboard when I go to reply to a comment:

![InkedScreenshot_20230709-113414](https://github.com/hjiangsu/thunder/assets/3624023/a16bafb3-eb8a-4ebb-bdd6-8e1b960338b0)

Not sure if it's present before the keyboard is shown, as I think it matches (or very closely matches) the background of the Create Comment popup. I'm also not seeing it when I go to create a new comment or a post, or edit my own comment - only in a reply. Odd!

If possible it would be good to remove, since it can at least partially obscure content on the screen when the parent comment is long enough (with the above screenshot as an example)

**Comment by hjiangsu** [comment]
Hmm, that might be something to do with it being scrollable - it might be adding some padding when the content can scroll.

Can you see if you can replicate this with a reply that's really short so that the content is not scrollable?

**Comment by machinaeZER0** [comment]
This happens for me even when the original comment is only one line long - in the attached screenshot the block/padding is covering up the clear/show preview buttons:
![Screenshot_20230709-153420](https://github.com/hjiangsu/thunder/assets/3624023/24943282-99cc-44da-bd25-4208fead2aff)

When I hide the keyboard the block isn't visible for me since it's the same color as the background. Mysterious!

**Comment by micahmo** [comment]
Could it be this? https://stackoverflow.com/a/49584482/4206279

**Comment by machinaeZER0** [comment]
That might be it! Where would that code need to go?

**Comment by micahmo** [comment]
According to the StackOverflow post, the problem is when there's a nested `Scaffold`. That was my case exactly. (If anyone's interested, I had to put the modal contents in a `Scaffold` in order for the snackbar to appear above the modal).

However, I'm not sure yet if that's the case here. There's a top-level `Scaffold` on the main page:

https://github.com/thunder-app/thunder/blob/082839abb85093c2ccec52640f8b8b6f1a390e66/lib/thunder/pages/thunder_page.dart#L157

But I don't see one in the `create_comment_modal`. I can try to look at this more later (if I can repro).

**Comment by hjiangsu** [comment]
Since there's the topic of nested scaffolds, I'll link this issue #250

The linked issue could be a general direction we can start heading towards, where we remove the nested scaffolds in favour of a single scaffold with internal "views". This is somewhat of a large change but it's one that I find would be beneficial for the structure of the app (and also remove this potential issue)

This would most likely happen in steps so that its a more gradual change but if you're interested in more of the details, feel free to check out the linked issue!

**Comment by ajsosa** [comment]
This issue was addressed with a complete redesign of the comment screen https://github.com/thunder-app/thunder/pull/643. Should be present in the next nightly and general release.

**Comment by machinaeZER0** [comment]
Hooray!
