### ISSUE TITLE
support spoiler tags

### ISSUE THREAD

**Issue by phareous** [thunder-app/thunder#304]
**Is your feature request related to a problem? Please describe.**

support spoiler tags in comments in the form of

::: spoiler label
Hidden text
:::

**Describe the solution you'd like**

Text hidden until you click on it

**Describe alternatives you've considered**

**Additional context**
![IMG_3549](https://github.com/hjiangsu/thunder/assets/1590943/55804e17-5e86-4228-8e98-6b07f9b75704)

**Comment by gon555551** [comment]
I really hope this gets implemented!!!

**Comment by hjiangsu** [comment]
For this, we would need to add in some custom logic to the Markdown parser to be able to detect spoiler tags as I think this is not something native to Markdown

Another point with this is that we should then support adding spoiler tags when creating or editing posts/comments

**Comment by CTalvio** [comment]
I did some experimenting with this.

Markdown does "support" collapsible content, like this:
```
<details>
  <summary>Spoiler warning</summary>
  
  Spoiler text. Note that it's important to have a space after the summary tag. You should be able to write any markdown you want inside the `<details>` tag... just make sure you close `<details>` afterward.
  
  ```javascript
  console.log("I'm a code block!");
  ```
  
</details>
```

But this is really working using html. This example works when testing with this: https://dart-lang.github.io/markdown/

But for obvious reasons, doesn't when using a flutter markdown library.

And Lemmy has it's own syntax for spoiler with the triple colon.

**Comment by micahmo** [comment]
I believe at some point we may need to fork `flutter_markdown` (which unfortunately is in a repo with all of the other first-party packages), since there are probably some other things we'd like to tweak as well (e.g., detecting `!` as part of a hyperlink for communities).

https://github.com/flutter/packages/tree/main/packages/flutter_markdown

**Comment by hjiangsu** [comment]
We might not need to fork the markdown package. I think you can extend the package to add in custom syntax logic: https://pub.dev/documentation/markdown/latest/markdown/ExtensionSet-class.html

**Comment by micahmo** [comment]
I started taking a look at this, and I think we may need to fork `flutter_markdown` after all.

For some background, I was able to add a custom `BlockSyntax` for parsing markdown spoilers. You can see it here.

https://gist.github.com/micahmo/9ed15cb884b79850a787816e1f9af497

Using just the `markdown` library, this syntax extension works great to generate HTML.

**Input**
``` dart
void main() {
  print(
    markdownToHtml(
      """### This is a title

This is a body
::: spoiler This is my spoiler title
This is my spoiler body
:::

And more...""",
      blockSyntaxes: [
        SpoilerBlockSyntax(),
      ],
    ),
  );
}
```

**Output**
``` html
<h3>This is a title</h3>
<p>This is a body</p>
<details><summary>This is my spoiler title</summary><a>This is my spoiler body</a></details>
<p>And more...</p>
```

**Rendered** 
| ![image](https://github.com/thunder-app/thunder/assets/7417301/ec2ba980-a893-4ebd-a08a-2a3b24611d7b) |
| - |

So far so good!

However, once we pass that through `flutter_markdown`, it fails. I believe this is because it doesn't account for nor have a way to style the `details` tag. Take a look at the supported tags here.

https://github.com/flutter/packages/blob/main/packages/flutter_markdown/lib/src/style_sheet.dart

As a result, I get a null issue on this line, where it assumes that the given `tag` will be in the list when it is not.

https://github.com/flutter/packages/blob/main/packages/flutter_markdown/lib/src/builder.dart#L632

If anyone else would like to give it a try and let me know if I'm missing something, I'd appreciate it!
