### ISSUE TITLE
In-app browser overflows below the navigation bar

### ISSUE THREAD

**Issue by bikasv** [thunder-app/thunder#324]
**Description**  
The in-app browser overflows below the navigation bar, making the bottom elements inaccessible. Often some websites are completely useless because at the bottom we've a GDPR notice to confirm/cancel, without which we can't proceed.

**How to Reproduce**  
1. Go to any post containing the URL
2. Click on the said URL
3. Observe the browser flowing below the navigation bar

**Expected Behavior**  
The browser should take into account of the navigation bar and shouldn't overflow.

**Screenshots**  
![Browser](https://github.com/hjiangsu/thunder/assets/1210099/bf1ca1ea-596b-4043-8fbd-ad26943a522a)

**Device & App Version:**  
 - Device: Samsung S21 Ultra
 - OS: Android 13 (One UI 5.1)
 - Version v0.2.1-alpha.1+12

**Comment by hjiangsu** [comment]
This might be fixable by adding a `SafeArea` surrounding the in-app browser

**Comment by hjiangsu** [comment]
This might be fixed with the change in #344

**Comment by bikasv** [comment]
Unfortunately it hasn't. I think along with SafeArea, we may need a height defined for the WebView and then overflow is to be added.

**Comment by hjiangsu** [comment]
Oh hmm, I haven't released a nightly which includes the change in #344. Did you happen to build to project as a test?

**Comment by micahmo** [comment]
I agree, I don't see any overflow with the new custom tabs.

| ![image](https://github.com/thunder-app/thunder/assets/7417301/a966fd6f-f4ee-48f1-887e-834369af58a3) |
| - |

@bikasv if you definitely have the latest and still see the issue, can you send another screenshot?

**Comment by bikasv** [comment]
Hi @hjiangsu,
I haven't tested by building it unfortunately. Yesterday I tested with v0.2.1-alpha.3+12.

Today when I tested with v0.2.1-alpha.4+12, I found that all the links are opening in default web browser instead of in-app. 

In addition to that, now the long images have problem with overflowing behind the navigation bar.

**Comment by bikasv** [comment]
Here's a short screen recording for the issue.

https://github.com/thunder-app/thunder/assets/1210099/6b1304c5-dd0f-4387-aefe-3e713deb933f

**Comment by micahmo** [comment]
> I found that all the links are opening in default web browser instead of in-app

Interesting! I'm sure this is a side-effect of switching to custom tabs. I wonder if it's because your default browser doesn't support it. May I ask what browser you're using? And is your phone de-Googled?

**Comment by bikasv** [comment]
I've Opera mobile, but if you're not using Chrome, you're going to face this issue.

Because even Brave, Vivaldi, and Firefox gave me the similar issue in the past.

**Comment by hjiangsu** [comment]
Hmm, it seems like its opening links in-app still, but because of custom tabs, it makes it feel like its opening up in the browser? Although I may be wrong since I don't have an Android

If you were to open up a link in Thunder, then go to your actual browser, is the link you opened up also there? If not, then it may just be opening up in-app even though it doesn't feel like it is

I think the long images overflowing can be solved by using `SafeArea` in the image viewer

**Comment by micahmo** [comment]
> I've Opera mobile, but if you're not using Chrome, you're going to face this issue.
> 
> Because even Brave, Vivaldi, and Firefox gave me the similar issue in the past.

I just tested all of the browsers that you mentioned and found some very interesting behavior.

#### Opera Mobile (running in Chrome custom tabs)

<img src="https://github.com/thunder-app/thunder/assets/7417301/0852bbed-a930-4a98-a6c8-e69f0b5e2505" width="250" />

#### Brave (running in Brave custom tabs)

<img src="https://github.com/thunder-app/thunder/assets/7417301/56cdeb28-8284-4fc8-895e-32c15f47bec5" width="250" />

#### Vivaldi (running in Vivaldi custom tabs)

<img src="https://github.com/thunder-app/thunder/assets/7417301/0a7caba1-0e51-44c7-a042-edf7e09f2420" width="250" />

#### Firefox (running in Firefox custom tabs)

<img src="https://github.com/thunder-app/thunder/assets/7417301/5252eecc-b730-40e4-988c-18f365874fc0" width="250" />

Then I disabled Chrome, and tried again. It used Brave Custom tabs. I uninstalled Brave, and it used Vivaldi. I uninstalled Vivaldi, it used Firefox. I uninstalled Firefox, and it finally opened Opera separately.

Here my conclusion...
 - If the default browser implements custom tabs, it is used.
 - If the default browser doesn't implement custom tabs, and Chrome is enabled, it is used.
 - If Chrome isn't available, any other app that uses supports custom tabs is used.
 - If none of the above are true, the default browser is opened.

I think Android actually does a great deal of due diligence to keep you in the app before resorting to a browser.

In my opinion, this issue is just a combination of the fact that Opera doesn't implement custom tabs, and you don't have any other browsers that do.

**Comment by bikasv** [comment]
Yeah, it looks that way. The only thing I can do is to have Chrome installed but not set default, and run everything else with Opera
