### ISSUE TITLE
Optional comment toolbar as alternative to gestures

### ISSUE THREAD

**Issue by SquawkWoof** [thunder-app/thunder#363]
**Is your feature request related to a problem? Please describe.**

The gestures are an interesting UI, but I find it less than optimal.

**Describe the solution you'd like**

Tap a comment to show/hide toolbar `upvote/downvote/save/reply/share/delete` (delete where applicable).  The "tap to collapse/expand child comments" function could be a button in the toolbar.

This could be optional functionality that disables the gestures when enabled.

**Describe alternatives you've considered**
 
n/a

**Additional context**

n/a

**Comment by micahmo** [comment]
You can already disable gestures and show buttons instead. But you would like the buttons to be hidden by default?

**Comment by SquawkWoof** [comment]
@micahmo: I've set:

 - `Posts > Disable swipe actions` to **ON**
 - `Navigation > Enable Swipe Gestures` to **OFF**
 - `Navigation > Enable Double-Tap Gestures` to **OFF**

Comments still require swipe actions to upvote/downvote/reply/favorite.  No buttons are displayed.

**Comment by micahmo** [comment]
What version are you using? The latest has a couple new options.

| ![image](https://github.com/thunder-app/thunder/assets/7417301/d0b19e05-87f9-4e53-a5ae-a7276f20751f) |
| - |

| ![image](https://github.com/thunder-app/thunder/assets/7417301/5e5f8037-4611-47ca-849f-894b8c2413d9) |
| - |

**Comment by SquawkWoof** [comment]
Ah!  Thank-you.  Only checked the readme, I didn't look at the release list itself.  I have the release from 2023-07-09.

**Comment by hjiangsu** [comment]
Hey! The latest release that contains this feature is technically a "pre-release" version which is why you were not able to see it.

While it does contain a lot of new features which are slated to be released in the upcoming general release, be aware that you may encounter more issues/bugs as it's not as widely tested yet! If you encounter any bugs or issues in these pre-releases, feel free to create issues for them to be addressed 😅
