### ISSUE TITLE
Consider moving post titles to appbar

### ISSUE THREAD

**Issue by CTalvio** [thunder-app/thunder#371]
Ideally, they would move there only when scrolling down, and persist to display what post you are scrolling.

**Comment by micahmo** [comment]
There was some discussion of this in #682. In fact, I had put "community: post title" in the AppBar. But after discussion and review of other apps, it was determined to simply put "Comments". Obviously we can revisit this issue or even make it optional if needed.

**Comment by micahmo** [comment]
@CTalvio Are you still interesting in having this feature? As you can see from #628, there's (a) not a lot of screen real estate to show titles, (b) most other apps do not show the title, and (c) the consensus of the (admittedly small) group of folks in that issue was to not show the title. Just wanted to get your thoughts on this one, since it's been a while! 😆

**Comment by CTalvio** [comment]
Nah, the appbar is used for other stuff now.

**Comment by micahmo** [comment]
Thanks for the feedback! I'll go ahead and close this issue then. 😊
