### ISSUE TITLE
Directly going to a subscribed community from sidebar ask you to back twice to quit the app

### ISSUE THREAD

**Issue by wadamT** [thunder-app/thunder#375]
**Description**  
When you go to a subscribed ~~instance~~ community directly from the sidebar of the home feed and when you back, normally it should return back to home feed. Now it is asking me to back twice to quit the application.

**How to Reproduce**  
1. Open the app
2. Go to an ~~instance~~ community under subscriptions from the sidebar of the home feed
3. Swipe back

**Expected Behavior**  
With one back, return back to home feed.

**Device & App Version:**  
 - OS: Android 9
 - App version: v0.2.1-alpha.5+12

**Comment by hjiangsu** [comment]
Could someone with an Android device test this and see if they can reproduce it? Unfortunately, I only have an iPhone which does not have the swipe back gesture

Pulling in @micahmo potentially for helping reproduce this issue!

**Comment by micahmo** [comment]
Yes I can reproduce this. I think it's "as intended" because the side bar is intended to let you switch what is displayed on the main page. Notice there's no UI back button on the community view. Also, for example if you switched to Local and pressed back, would you expect it to go to All?

So I think there's just a difference in expectations. That said, I understand that you want to go "home" when you press back, so I think we can probably make that work.

**Comment by machinaeZER0** [comment]
Sorry I missed this before posting my thoughts in the matrix discussion! (And apologies if people have weighed in over there, I don't have a matrix client on my phone yet)

I personally don't think of the subscriptions in the sidebar the same way I think of the different filters above them (subscribed/local/main), since they take you to specific communities with their own unique properties (banner top bar, community info, ability to post and subscribe), so I feel pretty strongly they should look the same whether you're navigating to them via a feed/post or through the sidebar.

I personally think that it would make sense to show the top and bottom UI across all pages, even though those pages are new views and not some sort of filtered version of the main feed. I believe Boost did this, and it means you always have a quick view of things like search, notifications, preferences and the like. While it obstructs more of your screen currently, the plan to hide top and bottom nav on scroll will make that a non-issue. I do think also that Boost took you back to your home feed by pressing Home or swiping to go back, which means you wouldn't need the currently implemented Back button in the current community view. 

Just my two cents (as always, hahah), so interested to hear others' opinions!

**Comment by micahmo** [comment]
Hey all,

I took a swing at this. Unsurprisingly, it's not as straightforward as we would like. 😄

I tried two different approaches. The first would behave like search where the community view gets pushed onto the navigation stack. One benefit to this approach is that the home page remains untouched. The downsides are that it doesn't feel quite right for how a navigation drawer works, it hides the bottom nav bar, and it doesn't support going back to your desired sort mode.

https://github.com/thunder-app/thunder/compare/develop...micahmo:thunder:feature/community-to-home-1

https://github.com/thunder-app/thunder/assets/7417301/b535d8f2-0241-4601-a6d9-f59753d121db

The other way I implememented is just by handling back and going to the default feed. Unfortuately, this also was not straightforward. Since, in this mode, we're not really "navigating" to the community, the "right" way of handling back via `WillPopScope` doesn't work. We can try to make the main Thunder page knowledgeable about community state, but that doesn't feel right either. So I pulled in [back_button_interceptor](https://pub.dev/packages/back_button_interceptor) to handle this very specific case. It seems to work fine and handles going to the desired sort mode.

https://github.com/thunder-app/thunder/compare/develop...micahmo:thunder:feature/community-to-home-2

https://github.com/thunder-app/thunder/assets/7417301/0f4eb224-8253-4859-b944-37b01d243272

I don't think either solution is perfect, but I also think we're planning on revisiting overall navigation at some point. Should I push either of these?

**Comment by machinaeZER0** [comment]
Sorry, thought I responded to this! I'd defer to others on their preferences, but from what I'm seeing in the video previews it feels like the second approach feels more like what I would expect from my experience with other apps. Not sure how far I'd want you to go down a rabbit hole if it's a hackier approach that would need to be redone later, but I do like it!

**Comment by micahmo** [comment]
> from what I'm seeing in the video previews, the second approach feels more like what I would expect from my experience with other apps

Sounds good! @wadamT Do you agree?

**Comment by wadamT** [comment]
@micahmo I agree. That's what I expect from swiping back action.
