### ISSUE TITLE
Any plans about the interface localization

### ISSUE THREAD

**Issue by History-exe** [thunder-app/thunder#398]
**Impressive App name and fluent operate experience.** But the interface is English only for now.

Already take a glance at the source code, seems can't easily do the localization work for the beginner like me. There is no integrated value file or strings file. Do you have the plan to make one or other solution for the international users.

I participated a few App localization, such as [Amadeus](https://github.com/Yink/Amadeus) and [Infinity-For-Reddit](https://github.com/Docile-Alligator/Infinity-For-Reddit). I can help with the zh-Hans part.

Your favorable consideration of this matter will be greatly appreciated.

**Comment by hjiangsu** [comment]
Localization is something that I hope to be able to get sometime in the near future, since I feel like there's a big benefit to having translations with such a wide audience. However, it'll take a bit of time to integrate that into the app!

**Comment by History-exe** [comment]
Thanks for reply. Wait patiently.

**Comment by hjiangsu** [comment]
There's been a little of progress on this end, but more work needs to be done still to fully support localization! I'm hoping to get this into the next next release if possible (v0.2.1+14 or v0.2.1+15)

**Comment by micahmo** [comment]
Just an update on this... any time the devs touch any area of code that includes hard-coded strings, we convert them to localizable strings. This is an ongoing effort, and I'm not sure we'll ever just do the whole thing at once. Most likely we'll keep going like this.

Also, once the strings _can_ be localized, it doesn't mean they _are_. We've had a few contributions early on, but there are still many things left to do. We had talked about setting up a Weblate instance, which is free for libre software.

Anyway, since this will always be an ongoing task, I'm not sure whether we want to keep this issue open, or close it now that the framework for localization is in place.

**Comment by hjiangsu** [comment]
I think we can keep this open up until we set up some workflow with Weblate to accept community translations! At that point, we can create a README section for translation and point contributors to that section for translations

**Comment by hjiangsu** [comment]
Since there's now a flow from Weblate to Thunder for localizations, I'll go ahead and close this! Feel free to contribute translations via Weblate and they'll be merged in on a periodic basis.
