### ISSUE TITLE
App crashing when loading images

### ISSUE THREAD

**Issue by ultram4ntis** [thunder-app/thunder#484]
**Description**  
I scroll through the app and when I click the thumbnail of an image to open it, there is a chance of the app crashing/freezing up. This does not happen on everything image, but seemingly at random. After having to force close I can load the same image and it will work fine.

This does not seem to occur with any other content, solely images

**How to Reproduce**  

Unable to as it seems to happen randomly 

**Expected Behavior**  
The app to load the image and not crash as it did previously 

**Device & App Version:**  
 - Device: Pixel 7
 - OS: Android 13, security update 5 July 2023

**Comment by hjiangsu** [comment]
How often does this tend to happen? 

My first assumption would've been that theres an issue with a specific image format, but since you mentioned that you can open the same image without issue the second time around, it might be something else.

Also, what version are you currently using, and are there any in-app settings that you have changed? (e.g., full height images, compact mode, etc)

**Comment by hjiangsu** [comment]
Given that there has not been any activity on this issue, I'll close it. Feel free to create a new issue if this problem is still occurring with the latest version! (0.2.7)
