### ISSUE TITLE
Add a "Swipe to reply" option for posts

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#566]
**Is your feature request related to a problem? Please describe.**
Currently you can only reply to/comment on a post if you open it and tap reply. It would be nice to swipe reply on a post the same way that you can swipe reply on a comment.

**Describe the solution you'd like**
Add the ability to swipe reply on a post the same way that you can swipe reply on a comment.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by hjiangsu** [comment]
This feature request can be up for discussion. I think we should lean away from adding this because it encourages a user to reply to a post without needing to open it or read through the comments of a given post.

I'd personally like the user to at least open the post before they reply to it so that they can take part in the discussion rather than to simply leave a comment without taking into account the context of the posts/comments

However, do feel free to let me know if there's a valid use case or scenario where this feature might be useful!

**Comment by K4LCIFER** [comment]
> I think we should lean away from adding this because it encourages a user to reply to a post without needing to open it or read through the comments of a given post.

That's a very fair point! I hadn't considered that, and I completely agree, now that I think about it.

**Comment by hjiangsu** [comment]
Closing this issue since it seems like we are on the same page!
