### ISSUE TITLE
Hyperlink URL previews

### ISSUE THREAD

**Issue by 1Phase1** [thunder-app/thunder#709]
**Is your feature request related to a problem? Please describe.**
As it is now, there's no way to know where a hyperlink leads besides just pressing it to open the link. It might be something you don't want appearing in your browsing history, or you'd just like to have some hint of what the hyperlink leads to before pressing it.

**Describe the solution you'd like**
A setting to make the top level domain of the URL embedded in a hyperlink visible in parentheses next to the hyperlink itself on comments. That way you can clearly see what site the link leads at a glance.

**Describe alternatives you've considered**
The only alternative now is pressing hyperlinks and letting them open a tab in your browser to see where they lead.

**Additional Context**
The following screenshot is an example of this feature as it appeared in Reddit Sync:

![Screenshot_20230906_010327](https://github.com/thunder-app/thunder/assets/69846246/2afa13eb-68d5-4424-9c33-f63a999459f3)

**Comment by micahmo** [comment]
Related to #309.

**Comment by micahmo** [comment]
I'm going to mark this as fixed in an upcoming release due to #869. However, note that the request in the original post was not exactly what was implemented. Rather than showing the domain inline, there is now the ability to preview the link with a long-press. @1Phase1 Feel free to take a look at the screen recording in the PR and let us know if that solution is sufficient. If not, we can revisit your specific request here!

**Comment by 1Phase1** [comment]
@micahmo I looked at the screen recording for the PR and I'm satisfied with the solution. Seems to be just fine. Thanks.
