### ISSUE TITLE
Remove overscroll effect when "remove animations" is checked

### ISSUE THREAD

**Issue by Jackthelad93** [thunder-app/thunder#758]
The one animation that persists even when "remove animations" is checked is the overscrolling effect, which is quite jarring if you're sensitive to motion effects. The ability to disable it alongside the other animations would be welcome.

**Comment by micahmo** [comment]
@Jackthelad93 Does the overscroll animation change at all? I believe in #163, @hjiangsu was able to change it from "stretching" to "bouncing" and there was some discussion about whether the latter is better. Maybe you can chime in on what you're seeing.

**Comment by Jackthelad93** [comment]
@micahmo Huh. Well, I just tried putting animations back on, and there's barely any overscroll effect at all. More like that "bouncing" effect you described, which is tolerable unlike the stretching effect.

It seems like the toggle is reversed when it comes to the overscroll. So I'm assuming that it's a bug.

**Comment by micahmo** [comment]
Thanks for the response! For clarify, I think we're using our terms in opposite ways. When I say "stretch" I mean that the top of the content is not moving, but rather the entirety of the page is essentially being elongated in the scroll direction. When I say "bounce" I mean that the page is being pulled past the top so that it is offset in the scroll direction. Maybe we need some videos. 😆

As for which is considered "reduced", bounce was chosen intentionally (it's not backwards). Take a look at the comments on #730 starting [here](https://github.com/thunder-app/thunder/pull/730#issuecomment-1716045209), and specifically the following.

> I think the main thing here is to remove that stretching effect that is caused when overscrolling because it causes some users to become nauseous when seeing that.
> 
> If everything is uniform and all the content moves uniformly across the screen, I think that would reduce that motion effect and hopefully reduce the nauseating feeling! My guess (but feel free to correct me here) is that reduce motion should reduce any "non-user" generated motion such as the stretch motion and navigation motion!

We had a lively debate about this and decided that the bounce was better than the stretch. However, neither of us being experts in accessibility issues. Or original goal was to remove any animation upon completion of scrolling, but that was proving difficult. In your opinion, is the stretch better than the bounce?

The original poster of #163 was unhappy with the stretch, which is what prompted our original change, but maybe we made it worse with the bounce.

**Comment by hjiangsu** [comment]
Hey @Jackthelad93, thanks for creating this issue! I think maybe we need to look at this a bit further then and adjust some of the expectations on how this should work. It would be great if someone with more accessibility knowledge could chime in as @micahmo mentioned 😄

> I think we're using our terms in opposite ways. When I say "stretch" I mean that the top of the content is not moving, but rather the entirety of the page is essentially being elongated in the scroll direction. When I say "bounce" I mean that the page is being pulled past the top so that it is offset in the scroll direction.

I think we might need some videos to differentiate between the overscroll effect (stretch) and the bounce 😅.

If we're unhappy with the overscroll/overstretch and bounce effects, I can propose the following change:
- When reduced animations setting is on, we completely eliminate the pull to refresh ability on pages that allow that currently.
- Instead, we'll allow the user to refresh the contents using a refresh button (which is already present in most pages)

If we go with this alternative, then we can both remove the overscroll/overstretch effects, and the bouncing effects hopefully. We'll have to run some tests to see if that is the case, but that's only if we want to go with this route.

**Comment by Jackthelad93** [comment]
@micahmo @hjiangsu I can't post a video on here, but whatever the effect is when animations are turned ON is fine for me. But the effect when animations are OFF is the jarring one.

If those effects could be swapped round, that would probably work.

**Comment by hjiangsu** [comment]
This is an example of what we mean by the over-scroll/overstretch:

https://user-images.githubusercontent.com/19204050/119530567-a65d8400-bd72-11eb-9785-7d8f840b7b8f.gif

Is this the jarring animation that you're mentioning? Unfortunately, I only have an iOS device, so I can't really test out the animation settings since it's always the bounce animation for me 😅

**Comment by Jackthelad93** [comment]
> This is an example of what we mean by the over-scroll/overstretch:
> 
> https://user-images.githubusercontent.com/19204050/119530567-a65d8400-bd72-11eb-9785-7d8f840b7b8f.gif
> 
> Is this the jarring animation that you're mentioning? Unfortunately, I only have an iOS device, so I can't really test out the animation settings since it's always the bounce animation for me 😅

Hopefully these GIFs work.

Here's with the animations turned OFF: 
![ezgif com-video-to-gif](https://github.com/thunder-app/thunder/assets/145712911/d192c587-7f90-41b6-8e91-7fdc0d0b0950)

And here's with the animations turned ON: 
![ezgif com-video-to-gif (2)](https://github.com/thunder-app/thunder/assets/145712911/84f0d3bd-d9a8-4e31-a45c-63990c319226)

As you can see, the effect is far more noticeable when the animations are off. The effect when animations are on however, is fine.

**Comment by micahmo** [comment]
> The effect when animations are on however, is fine.

That's great feedback! Just keep in mind that #163 was opened in relation to the effect which you see when animations are _on_. I'm glad that animation doesn't bother you much, but it did bother (or at least was noticed by) @Coffee-Viking, which is what prompted the change.

I like @hjiangsu's suggestion of removing pull-to-refresh in order to completely remove any animation whatsoever. If we have pull-to-refresh on a page that doesn't also have another way of refreshing (AppBar button, FAB), then we should add a second way.

**Comment by Jackthelad93** [comment]
@micahmo Removing pull-to-refresh would be fine for me because I sometimes use the refresh button in the top bar anyway.

**Comment by hjiangsu** [comment]
> I like @hjiangsu's suggestion of removing pull-to-refresh in order to completely remove any animation whatsoever. If we have pull-to-refresh on a page that doesn't also have another way of refreshing (AppBar button, FAB), then we should add a second way.

I have managed to figure out an alternative that doesn't remove the pull-to-refresh functionality. I did some testing on an emulator and it seems to work, but it might vary with a physical device. You can see the associated PR that was created for this issue!
