### ISSUE TITLE
Unresponsiveness while loading communities

### ISSUE THREAD

**Issue by kovalensky** [thunder-app/thunder#789]
**Description**  

While choosing communities from the sidebar it's not possible to re-choose community if one is already loading.
I think requests should be async.

Also sometimes there's an undebuggable bug happening. Sometimes while Thunder is trying to load the home page it stucks and keeps loading endlessly and due to previous bug I can't change the community to reinitialize a new request, then I have to close and re-open the app.

**Screenshots**  

As you can see without matter how many times I click another community it will load the first chosen one:

https://github.com/thunder-app/thunder/assets/45331093/c1d27cd8-8394-4b2b-aed4-b7f11b2e604a

**Device & App Version:**  
 - OS: Android 10, MIUI 12.5
 - Version: 0.2.4

**Comment by kovalensky** [comment]
@hjiangsu Any opinions my asian bro? :D

**Comment by hjiangsu** [comment]
> While choosing communities from the sidebar it's not possible to re-choose community if one is already loading.
I think requests should be async.

This seems to be due to the fact that we debounce/throttle requests on our end to limit the number of requests that gets sent to an instance in cases of spam. This means that performing multiple repeated actions in quick succession may sometimes not work because Thunder throttles it. We can play around with this value and find a more reasonable compromise, but this is what I assume is happening.

> Also sometimes there's an undebuggable bug happening. Sometimes while Thunder is trying to load the home page it stucks and keeps loading endlessly and due to previous bug I can't change the community to reinitialize a new request, then I have to close and re-open the app.

This sounds like a network issue, but I'm not too sure as there's not much info here. If you encounter it again, try to notice the conditions that it happens in (cellular service vs WiFi, network related issues, switch in connection, etc.) and open a new issue with those details if possible.

On a different note, I would also like to give a quick reminder that discussions on here should abide by our [code of conduct](https://github.com/thunder-app/thunder/blob/develop/CODE_OF_CONDUCT.md) to allow for a safe and inclusive space for everyone involved.

**Comment by kovalensky** [comment]
> This sounds like a network issue, but I'm not too sure as there's not much info here.

I have a stable uplink (27mbit), this happens randomly, could be an instance slowing down others, or something in that matter, I think there should be some kind of connection repeating mechanism, since it seems Thunder is not doing ot,  I'm not able to debug it.

I'm familiar with the code of conduct, it's also important to have a good mood in conversations without having any agression towards other person, jokes could be harmless and funny ;)

**Comment by kovalensky** [comment]
I was able to capture the homepage bug behaviour, as you can see it loads another tabs, but not communities.

https://github.com/thunder-app/thunder/assets/45331093/6690a8dc-eed0-4364-af13-957a238aab3a

**Comment by hjiangsu** [comment]
> I was able to capture the homepage bug behaviour, as you can see it loads another tabs, but not communities.

Hmm, thats odd. How often would you say this happens? Also, is there a specific instance that this happens more often than another? (e.g., `lemm.ee` vs `lemmy.world`)

I know there was previously an issue where Thunder would hang if a given instance was down. This issue was fixed recently in #770 but I'm not sure if these two issues are related in any way.

**Comment by kovalensky** [comment]
> How often would you say this happens?

Randomly, it could once a day or not happen.

> Also, is there a specific instance that this happens more often than another?

My account is on lemm.ee, I can't say this is related to them, bacause I can't be sure, but it will load if I reopen the app.

Are there any solutions to send logs or debug it?

**Comment by kovalensky** [comment]
> Sorry for the late response! Unfortunately, there's no way to send back logs or debug it with a release build at this time. I will keep an eye out for this, but let me know if the latest nightly build fixes this issue.
> 
> I have also adjusted the logic for the throttling to hopefully allow the initial issue to be more responsive. Assuming all goes well, I'll add this fix to the next nightly build.

Sure thing asian bro :)
I'm happy that you made enhancements.

I'm using nightly now, I tried choosing communities again without luck, but I've read your patch, I think its due to artificial limits against race condition, I've seen crashes two times this day, I think this is an overflow, my whole system freezes after Thunder stops responding:


https://github.com/thunder-app/thunder/assets/45331093/bc727b40-f463-4793-82a5-6864be81a97d

**Comment by hjiangsu** [comment]
> I'm using nightly now, I tried choosing communities again without luck

The fix was not released in the previous nightly. However, it should be released in the current nightly `0.2.5-2`. Let me know if you're still experiencing this issue

**Comment by kovalensky** [comment]
Oh yeah, sorry asian bro, I had a hard schedule those days, then I forgot :/, great patch, I didn't see any freezes since then, thank you for all the dev feedback.
💚
