### ISSUE TITLE
"Message User" button is greyed out, and non-functional

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#793]
**Description**  
The message user button is greyed out, and non-functional

**How to Reproduce**  
1. Go to a user profile
2. Observe that the "Message User" button is greyed out
3. Tap the message user button
4. observe that nothing happens

**Expected Behavior**  
I expect the message user button to work

**Screenshots**  
![Screenshot_20231001-150249](https://github.com/thunder-app/thunder/assets/7829231/c65ab82c-5a40-4832-b19e-e85fc79253b3)

**Device & App Version:**  
 - Device: Pixel 6
 - OS: Android 14
 - Thunder v0.2.4

**Additional Context**  
None.

**Comment by micahmo** [comment]
Thanks for the report. This button was added as a placeholder in #419, but was never actually implemented. Personally I would probably hide buttons that are not yet functional (especially in general releases), but that's just me and I'm not trying to knock anyone!

@hjiangsu What do you think about hiding this button until it's implemented. Then we should probably change this issue to an enhancement since it's really a new (and big!) feature.

**Comment by hjiangsu** [comment]
Yeah, I agree with this. We should hide this button (or any buttons that are no currently functional) from view until its completed!
